version: '3.9'

services:
  frontend:
    build:
      context: ./chat-app
    container_name: chat-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    command: [ "npm", "run", "dev" ]
    volumes:
      - ./chat-app:/app
      - /app/node_modules
  server:
    build:
      context: ./server
    container_name: chat-server
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./server:/server
